project setup
banlon-jones/bookstore pull request #1
Opened 2022-02-22 00:15 UTC by banlon-jones

# project setup
- Add React Redux
- added Navbar component
- added the AddNewBook component
- added the ListBook component
- added the Book item component
- added the categories page
- added the books page

2022-02-22 01:02 UTC, Gambit142 requested changes
Hi @banlon-jones 👋, 

Good job so far!

### Highlights
✅ All linters checks passed
✅ Proper implementation of project setup

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-22 01:02 UTC, Gambit142 commented on package.json
> +    "react-router-dom": "^6.2.1",
- [ ] Nice job setting up this app with the `create-react-app` command. Kindly install `react-redux` as a dependency for this project. Although you do not need it now, it is part of your project requirement and it would help you kickstart your next milestone.

2022-02-22 01:02 UTC, Gambit142 commented on src/components/add-new-book/AddNewBook.js
> +    </div>
- [ ] It would be nice to gather the information from your form and pass it as props to your `BookItem` component where the form values for `author` and `categories` will be rendered. 

_**Hint**_: It involves you using React hook's `UseState` together with `onClick` and `onChange` event handlers. You can read this [article](https://www.pluralsight.com/guides/how-to-send-state-of-current-component-as-a-parameter-to-another-external-method-using-react) to give you an idea about how to go about it.

2022-02-22 08:36 UTC, banlon-jones commented on src/components/add-new-book/AddNewBook.js
> +    </div>
Hi @Gambit142 , 
thanks for the feedback
but these are the project requirements
- Should display the list of books (empty at this point but it should be ready for the data) with the Remove button (no funcionality yet)
- Should have a form for adding a book (no functionality yet)
- Should have a form for adding a book (no functionality yet)
- Should display "Under construction" text only.

2022-02-22 09:25 UTC, dasileker approved these changes
## **Hi @banlon-jones,** 

## **Congratulations! 🎉 Project Approved ✅**
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-22 10:21 UTC, merged

2022-02-23 12:01 UTC, Gambit142 commented on src/components/add-new-book/AddNewBook.js
> +    </div>
Hi @banlon-jones, I am sorry about that, I am glad your project was approved. Sorry for any inconvenience caused.